#!/bin/bash
set -e

source_dir_path="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

case "$1" in
    "-i")
        data_path="$2"; shift 2
        hbs "$source_dir_path/interactive.hbs.sh" "$data_path" "$source_dir_path"/*.js
        exit
        ;;

    "-h")
        cat "$source_dir_path/libslave.h"
        exit
        ;;
esac

data_path="$1"; shift
hbs "$source_dir_path/libslave.hbs.c" "$data_path" "$source_dir_path"/*.js
